API_KEY=HARSH_MONUMENT_SECRET_2026
DATABASE_URL=jdbc:postgresql://dpg-d6c8phftn9qs73d42m60-a.singapore-postgres.render.com/monumentdb
DATABASE_USERNAME=monumentuser
DATABASE_PASSWORD=OYiXSSa6mwQFDX8Y8Wtfy0mvTPJ6J13q
