spring.application.name=monument-info
spring.datasource.url=jdbc:postgresql://dpg-d6c8phftn9qs73d42m60-a.singapore-postgres.render.com/monumentdb
spring.datasource.username=monumentuser
spring.datasource.password=OYiXSSa6mwQFDX8Y8Wtfy0mvTPJ6J13q

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

app.api.key=HARSH_MONUMENT_SECRET_2026